CREATE TABLE MAQUINA(
	ID_MAQUINA INT PRIMARY KEY AUTO_INCREMENT,  -- AUTO_INCREMENT: Onde o banco cuidará da chave primária.
	NOME VARCHAR(100) NOT NULL, -- NOT NUL: Obrigatório ter o registro.
	MODELO VARCHAR(50) NOT NULL,
	FABRICANTE VARCHAR(100) NOT NULL,
	DATA_AQUISICAO DATE NOT NULL,
	STATUS_OPERACIONAL ENUM ('Ativa', 'Inativa', 'Manutenção') NOT NULL
);

CREATE TABLE MANUTENCAO(
	ID_MANUTENCAO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('preditiva','preventiva','corretiva') NOT NULL,
	CUSTO DECIMAL(10,2) NOT NULL,
	DURACAO_HORAS INT NOT NULL,
	TECNICO_RESPONSAVEL VARCHAR(100) NOT NULL,
	ID_MAQUINA INT,

	FOREIGN KEY(ID_MAQUINA)
	REFERENCES MAQUINA(ID_MAQUINA)
);

CREATE TABLE INCIDENTE(
	ID_INCIDENTE INT PRIMARY KEY AUTO_INCREMENT,
	DESCRICAO VARCHAR(255) NOT NULL,
	SEVERIDADE ENUM ('leve', 'baixa','moderada', 'alta', 'extrema') NOT NULL,
	RISCO ENUM('Baixo', 'Médio', 'Alto') NOT NULL,
	ID_MAQUINA INT,

	FOREIGN KEY(ID_MAQUINA)
	REFERENCES MAQUINA(ID_MAQUINA) 	
);
